[tool.poetry]
name = "to-ascii"
version = "5.0.0"
description = "Convert videos, images, gifs, and even live video to ASCII art!"
authors = ["Milo Weinberg <iapetus011@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.1"
opencv-python = "^4.6.0"
colorama = "^0.4.5"
nimporter = { version = "^1.1.0", optional = true}
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"

[tool.poetry.extras]
speedups = ["nimporter"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
